version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: alimenti-front
    volumes:
      - ./certs/alimenti.io.crt:/etc/ssl/certs/alimenti.io.crt
      - ./certs/alimenti.io.key:/etc/ssl/private/alimenti.io.key
      - ./certs/cloudflare.crt:/etc/ssl/certs/cloudflare.crt
      - ./cloudflare.txt:/etc/nginx/cloudflare
    ports:
      - "80:3000"
      - "443:3000"
    restart: unless-stopped
