version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: flt-frontend
    environment:
      - NODE_ENV=development
    env_file:
    - ./.env.development
    ports:
      - "3000:3000"
    restart: unless-stopped
