version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: alimenti-front
    env_file:
      - .env.front.production
    volumes:
      - ./certs/alimenti.io.pem:/etc/ssl/certs/alimenti.io.pem
      - ./certs/alimenti.io.key:/etc/ssl/private/alimenti.io.key
      - ./certs/cloudflare.crt:/etc/ssl/certs/cloudflare.crt
    ports:
      - "80:3000"
    restart: unless-stopped
