version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: alimenti-front
    env_file:
      - .env.front.production
    ports:
      - "80:3000"
    restart: unless-stopped
