version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: flt-frontend
    env_file:
    - ./.env.production
    ports:
      - "3000:80"
    restart: unless-stopped
