version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: alimenti-front
    env_file:
      - .env.front.development
    ports:
      - "3000:3000"
    restart: unless-stopped
