version: '3.8'
services:
  app:
    container_name: alimenti-front
    image: index.docker.io/mcanziani1/alimenti-front:latest
    env_file:
      - .env.front.production
    volumes:
      - ./certs/alimenti.io.crt:/etc/ssl/certs/alimenti.io.crt
      - ./certs/alimenti.io.key:/etc/ssl/private/alimenti.io.key
      - ./certs/cloudflare.crt:/etc/ssl/certs/cloudflare.crt
      - ./cloudflare-ips.conf:/etc/nginx/cloudflare-ips.conf
    networks:
      - local_net
    depends_on:
      - api
    ports:
      - "80:3000"
      - "443:3000"
  api:
    container_name: alimenti-back
    image: index.docker.io/mcanziani1/alimenti-server:latest
    env_file:
      - .env.server.production
    networks:
      - local_net
    ports:
      - "7500:7500"
  watchtower:
    image: containrrr/watchtower
    environment:
        DOCKER_CONFIG: /config
    volumes:
      - /etc/watchtower/config/:/config/
      - /var/run/docker.sock:/var/run/docker.sock
    command: --interval 30
networks:
  local_net:
    driver: bridge
