version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.prod
    container_name: food-log-tracker
    environment:
      - NODE_ENV=production
    volumes:
      - ./logs/server:/usr/src/app/logs
    ports:
      - "7500:7500"
    restart: unless-stopped
