version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: alimenti-server
    env_file:
      - .env.server.development
    volumes:
      - ./logs/server/:/app/logs/server/
    ports:
      - '7500:7500'
    restart: unless-stopped
