version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: flt-server
    environment:
      - NODE_ENV=development
      - VITE_PORT=7500
    volumes:
      - ./logs/server/:/app/logs/server/
    ports:
      - '7500:7500'
    restart: unless-stopped
