name: Build Containers for Prod & Push to Dockerhub

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  build-and-deploy-back:
    name: Build and Deploy Server
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: server/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/alimenti-server:latest
        env:
          FIREBASE_SERVICE_ACCOUNT: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_KEY }}

  build-and-deploy-front:
    name: Build and Deploy FrontEnd
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: frontend/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/alimenti-front:latest
        env:
          FIREBASE_CONFIG: ${{ secrets.FIREBASE_CONFIG }}
      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.PI_SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H '${{ secrets.PI_IP }}' >> ~/.ssh/known_hosts
      - name: Copy docker-compose.yml to Droplet
        run: |
          scp ./docker-compose.yml alimenti@${{ secrets.PI_IP }}:~/devops/docker-compose.yml
      - name: Copy nginx.conf to Droplet
        run: |
          scp ./nginx/nginx.conf alimenti@${{ secrets.PI_IP }}:~/devops/nginx.conf
      - name: SSH and Docker Compose Up
        run: |
          ssh alimenti@${{ secrets.PI_IP }} 'cd ~/devops && docker compose pull && docker compose up -d'