name: Build Containers for Prod & Push to Dockerhub

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    name: Build and Deploy Containers
    runs-on: self-hosted

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and Push Server Image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: server/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/alimenti-server:latest
        env:
          FIREBASE_SERVICE_ACCOUNT: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_KEY }}

      - name: Build and Push FrontEnd Image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: frontend/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/alimenti-front:latest
        env:
          FIREBASE_CONFIG: ${{ secrets.FIREBASE_CONFIG }}

      - name: Deploy with Docker Compose
        run: |
          # Navigate to the deployment directory
          cd ~/devops

          # Optional: Pull the latest docker-compose.yml from the repository if not already present
          # cp ./path/to/docker-compose.yml .

          cp ~/actions-runner/_work/FoodSymptomTracker/FoodSymptomTracker/docker-compose.yml ~/devops/docker-compose.yml
          cp ~/actions-runner/_work/FoodSymptomTracker/FoodSymptomTracker/nginx/nginx.conf ~/devops/nginx.conf

          # Pull the latest images from Docker Hub
          docker compose pull

          # Restart the containers with the latest images
          docker compose up -d